spring:
  application:
    name: utility-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default profile
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 200
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

spring-batch:
  chunk-size: 200

mpay:
  security:
    jwt:
      secret: 7b3f9e2a5c8d1b4a6f0e2d5c8b1a4f7e0d3c6b9a2f5e8d1c4b7a0f3e6d9c2b5a